- build.gradle
> Fixing Gradle Build Failure

- build.gradle
> Setting the SonarCloud Project Key

- build.gradle
> Changing Spring Boot version to 2.5.6

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateGeneralApplicationHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/CreateGeneralApplicationHandlerTest.java
> Adding Application Summary Message

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/InitiateGeneralApplicationHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/InitiateGeneralApplicationHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-660
1. fix general application types display
2. remove SET_ASIDE_JUDGEMENT general application type.
```
[ ] Yes
[X] No
```
> fix general application types display

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/InitiateGeneralApplicationHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/model/genapplication/GAPbaDetails.java
https://tools.hmcts.net/jira/browse/CIV-728
Changing the pba account list to DynamicList
```
[ ] Yes
[ ] No
```
> CIV-728 Change the pojo in accordance with ccd-model change

- src/main/java/uk/gov/hmcts/reform/civil/enums/dq/GeneralApplicationTypes.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/InitiateGeneralApplicationHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-737
Fix the application type as per the prototype
```
[ ] Yes
[X] No
```
> CIV-737 Fix the application type as per the prototype

- src/main/java/uk/gov/hmcts/reform/civil/model/genapplication/GAHearingDetails.java
- src/main/java/uk/gov/hmcts/reform/civil/model/genapplication/GAUnavailabilityDates.java
https://tools.hmcts.net/jira/browse/CIV-727
Model changes after ccd screen changes
```
[ ] Yes
[X] No
```
> CIV-727 Hearing screen details model changes

- src/test/java/uk/gov/hmcts/reform/civil/handler/tasks/GeneralApplicationTaskHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataBuilder.java
> Sonar Qube Build Failure Fix

- Jenkinsfile_CNP
> Removing Pact Test

- Jenkinsfile_CNP
> Fixing AAT Env Deployment

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/GeneralApplicationCreationNotificationHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/NotificationData.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/tasks/CreateApplicationTaskHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/helpers/DateFormatHelper.java
- src/main/java/uk/gov/hmcts/reform/civil/model/CaseData.java
- src/main/java/uk/gov/hmcts/reform/civil/model/genapplication/GeneralApplication.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/GeneralApplicationCreationNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/tasks/CreateApplicationTaskHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataBuilder.java
> notification on submit

- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/GeneralApplicationCreationNotificationHandlerTest.java
> fix claimant or respondent test

- src/main/java/uk/gov/hmcts/reform/civil/enums/GeneralApplicationTypes.java
- src/main/java/uk/gov/hmcts/reform/civil/enums/dq/GeneralApplicationTypes.java
https://tools.hmcts.net/jira/browse/CIV-1344
UI changes as mentioned in jira
```
[ ] Yes
[X] No
```
> CIV-1344 Add 2 more application types

- src/main/java/uk/gov/hmcts/reform/civil/enums/CaseState.java
https://tools.hmcts.net/jira/browse/CIV-778
Add the parent case states as otherwise the casedata deserialization fails at the first event of camunda flow.
```
[ ] Yes
[X] No
```
> CIV-778 Add missing states

- src/main/java/uk/gov/hmcts/reform/civil/enums/dq/GAJudgeDecisionOption.java
- src/main/java/uk/gov/hmcts/reform/civil/model/CaseData.java
- src/main/java/uk/gov/hmcts/reform/civil/model/genapplication/GAJudicialDecision.java
https://tools.hmcts.net/jira/browse/CIV-80
Judge's screen
```
[ ] Yes
[X] No
```
> CIV-80 Judge screen - judicial decision

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/caseassignment/AssignCaseToUserCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/GeneralApplicationCreationNotificationHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/model/CaseData.java
- src/main/java/uk/gov/hmcts/reform/civil/model/genapplication/GeneralApplication.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/businessprocess/EndGeneralAppBusinessProcessCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/notification/GeneralApplicationCreationNotificationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/caseassignment/AssignCaseToUserHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataBuilder.java
Remove following fields as it's no longer required. All the logic for assigning roles to user is done in CIV-1290
1. applicantSolicitor1UserDetails;
2. applicant1OrganisationPolicy;
3. respondent1OrganisationPolicy;
```
[x] Yes
[ ] No
```
> CIV-1290 Refactor Existing code

- bin/variables/load-staging-environment-variables.sh
- charts/civil-general-applications/values.aat.template.yaml
> preview environment

- Jenkinsfile_CNP
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/model/genapplication/GAJudicialMakeAnOrder.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-1633
add direction-response date to model and handle callback to validate it
```
[ ] Yes
[X] No
```
> Feature/civ 1633 add direction-response date to model and handle callback to validate it

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/civil/enums/dq/GAJudgeRequestMoreInfoOption.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/model/CaseData.java
- src/main/java/uk/gov/hmcts/reform/civil/model/genapplication/GAJudicialRequestMoreInfo.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-82
CIV-82 Judge's journey : Request more information screen
```
[ ] Yes
[X] No
```
> CIV-82 Judge's journey : Request more information screen

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/model/genapplication/GAJudgesHearingListGAspec.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-1720
https://github.com/hmcts/civil-general-apps-ccd-definition/pull/105
Create textarea to populate the hint text in hearing screen
```
[x] Yes
[ ] No
```
> CIV-1720 Fix Hint Text in Hearing page

- Jenkinsfile_CNP
- charts/civil-general-applications/values.aat.template.yaml
- charts/civil-general-applications/values.preview.template.yaml
- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/civil/enums/GAJudicialHearingType.java
- src/main/java/uk/gov/hmcts/reform/civil/enums/dq/GAJudgeRequestMoreInfoOption.java
- src/main/java/uk/gov/hmcts/reform/civil/enums/dq/GAJudgeWrittenRepresentationsOptions.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/model/CaseData.java
- src/main/java/uk/gov/hmcts/reform/civil/model/genapplication/GAJudgesHearingListGAspec.java
- src/main/java/uk/gov/hmcts/reform/civil/model/genapplication/GAJudicialMakeAnOrder.java
- src/main/java/uk/gov/hmcts/reform/civil/model/genapplication/GAJudicialRequestMoreInfo.java
- src/main/java/uk/gov/hmcts/reform/civil/model/genapplication/GAJudicialWrittenRepresentations.java
- src/main/java/uk/gov/hmcts/reform/civil/service/JudicialDecisionService.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/JudicialDecisionServiceTest.java
> Judges integration

- bin/variables/load-staging-environment-variables.sh
- charts/civil-general-applications/values.aat.template.yaml
> adding civil service to aat charts

- bin/variables/load-staging-environment-variables.sh
- charts/civil-general-applications/values.aat.template.yaml
> updated xui igress host

- Jenkinsfile_CNP
- charts/civil-general-applications/values.aat.template.yaml
> updated ingress host for xui

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-1818
CIV-1818 Populate Judges Order with Draft Order from Applicant
```
[ ] Yes
[X] No
```
> CIV-1818 Populate Judges Order with Draft Order from Applicant

- src/main/java/uk/gov/hmcts/reform/civil/model/genapplication/GAJudicialWrittenRepresentations.java
https://tools.hmcts.net/jira/browse/CIV-1866
Days to Date for Written Representations - Sequential Representations
```
[ ] Yes
[X] No
```
> Days to Date for Written Representations - Sequential Representations

- src/main/java/uk/gov/hmcts/reform/civil/service/JudicialDecisionService.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/JudicialDecisionServiceTest.java
https://tools.hmcts.net/jira/browse/CIV-1866
add applicant date validation
```
[ ] Yes
[X] No
```
> add applicant date validation

- Jenkinsfile_CNP
- src/main/java/uk/gov/hmcts/reform/civil/model/genapplication/GAJudgesHearingListGAspec.java
> Sprint5integration

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-1872
```
[ ] Yes
[X] No
```
> Add 7 day txt

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandlerTest.java
> dot after 7 day txt

- charts/civil-general-applications/Chart.yaml
- charts/civil-general-applications/values.yaml
- config/owasp/suppressions.xml
Attempting to fix error
`synchronization of release 'civil-general-applications' in namespace 'civil' failed: installation failed: poddisruptionbudgets.policy "civil-general-applications-java" already exists
`
```
[ ] Yes
[X] No
```
> Attempting to fix pdb error

- Jenkinsfile_CNP
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToApplicationHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/model/CaseData.java
- src/main/java/uk/gov/hmcts/reform/civil/utils/RespondentsResponsesUtil.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToApplicationHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-1754
https://github.com/hmcts/civil-general-apps-ccd-definition/pull/127/files
```
[ ] Yes
[ ] No
```
> CIV-1754 Change hearing label for Urgent application

- .gitignore
- Jenkinsfile_CNP
- build.gradle
- src/contractTest/java/uk/gov/hmcts/reform/civil/IdamConsumerTest.java
https://tools.hmcts.net/jira/browse/CIV-1547
PACT initial changes for civil-general-applications
```
[ ] Yes
[ ] No
```
> CIV-1547 PACT testing

- src/main/java/uk/gov/hmcts/reform/civil/enums/dq/GeneralApplicationTypes.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToApplicationHandler.java
https://tools.hmcts.net/jira/browse/CIV-1976
https://github.com/hmcts/civil-service/pull/882
https://github.com/hmcts/civil-ccd-definition/pull/702
https://github.com/hmcts/civil-general-apps-ccd-definition/pull/133
'Amend a stmt of case'. expand the word 'stmt' to 'statement'.
Change the Respondent confirmation screen text. Change the word 'info' to 'information
```
[ ] Yes
[ ] No
```
> CIV-1976 Text change

- config/owasp/suppressions.xml
added new
```
[ ] Yes
[ ] No
```
> sprint6 integration branch 

- bin/variables/load-staging-environment-variables.sh
- charts/civil-general-applications/values.aat.template.yaml
> updated ingress host for civil service

- bin/variables/load-staging-environment-variables.sh
- charts/civil-general-applications/values.aat.template.yaml
> updated charts with correct civil service host

- charts/civil-general-applications/Chart.yaml
- charts/civil-general-applications/values.preview.template.yaml
> update helm chart version

- src/main/java/uk/gov/hmcts/reform/civil/service/PaymentsService.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataBuilder.java
- src/test/java/uk/gov/hmcts/reform/civil/service/PaymentsServiceTest.java
https://tools.hmcts.net/jira/browse/CIV-2253
Add Fee version validation to stop hard failure.
```
[ ] Yes
[ ] No
```
> CIV-2253 Add validation on fee-version

- charts/civil-general-applications/values.aat.template.yaml
- charts/civil-general-applications/values.preview.template.yaml
> updated charts to take up new vault values

- Jenkinsfile_CNP
- src/main/java/uk/gov/hmcts/reform/civil/model/genapplication/GeneralApplication.java
> Sprint1integration

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandler.java
https://tools.hmcts.net/jira/browse/CIV-2580
General order and Dismissal order details should be retain
```
[ ] Yes
[ ] No
```
> CIV-2580 Save General Order Text and Dismissal Order text in DB

- src/main/java/uk/gov/hmcts/reform/civil/enums/GAJudgeOrderClaimantOrDefenseFixedList.java
https://tools.hmcts.net/jira/browse/CIV-2275
https://github.com/hmcts/civil-ccd-definition/pull/832
https://github.com/hmcts/civil-general-apps-ccd-definition/pull/177
For Which Document dropdown - change Defense to Defence.
Add document types to upload files component text. To include doc, docx, dot, pdf, rtf, xlt or xlsx On Applicant Screen and Upload screens
```
[ ] Yes
[ ] No
```
> CIV-2275 Fix typo and add pdf types

- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/DocmosisTemplates.java
https://tools.hmcts.net/jira/browse/CIV-2512
Update on GA for new file name
```
[ ] Yes
[X] No
```
> Update on GA Template for new file name

- build.gradle
> Botdependenciesupgrade

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GeneratePDFDocumentCallbackHandler.java
https://tools.hmcts.net/jira/browse/CIV-3006
fixed the bug when the option fields is unchecked 
```
[ ] Yes
[x] No
```
> fixed the bug when the option field are unchecked

- src/main/java/uk/gov/hmcts/reform/civil/service/GeneralAppLocationRefDataService.java
- src/test/java/uk/gov/hmcts/reform/civil/service/GeneralAppLocationRefDataServiceTest.java
https://tools.hmcts.net/jira/browse/CIV-3025
Update Court dropdown on Judges Hearing screen to show "Court Name", "Address", "Postcode"
```
[ ] Yes
[X] No
```
> Modified location data by adding court address

- charts/civil-general-applications/values.aat.template.yaml
- charts/civil-general-applications/values.preview.template.yaml
> added genapp lrd url

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandler.java
https://tools.hmcts.net/jira/browse/CIV-3143
Multi party scenarios are throwing null pointer exception when we dont select support requirements in Applicant and respondent journeys
```
[ ] Yes
[x] No
```
> Null check for hearing requirements and code refactor

- Jenkinsfile_CNP
> Update Jenkinsfile_CNP for include lrspec

- build.gradle
- config/owasp/suppressions.xml
> Dependencycheckupgrade

- src/main/java/uk/gov/hmcts/reform/civil/enums/CaseState.java
- src/main/java/uk/gov/hmcts/reform/civil/service/StateGeneratorService.java
- src/test/java/uk/gov/hmcts/reform/civil/service/StateGeneratorServiceTest.java
1) order made is when we make an order for any application type and its approved. 
2) if its the claimant of the main case who has made the general application of application type strike out and an order has been made by the judge as a decision then we change the status to proceed in heritage.
```
[x ] Yes
[ ] No
```
> CIV-780 Status changes while making an order

- Jenkinsfile_CNP
- charts/civil-general-applications/values.aat.template.yaml
- charts/civil-general-applications/values.preview.template.yaml
> jenkins cnp changes and chart changes

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandler.java
updateDirectionOrderText
https://tools.hmcts.net/jira/browse/CIV-3724
updateDirectionOrderText
```
[ ] Yes
[X] No
```
> CIV-3724 updateDirectionOrderText

- src/main/java/uk/gov/hmcts/reform/civil/model/CaseData.java
- src/main/java/uk/gov/hmcts/reform/civil/service/SolicitorEmailValidation.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataBuilder.java
- src/test/java/uk/gov/hmcts/reform/civil/service/SolicitorEmailValidationTest.java
> Fix update solicitor email for 2v1 case

- build.gradle
- config/owasp/suppressions.xml
> vulnerability fix

- build.gradle
- config/owasp/suppressions.xml
Reverts hmcts/civil-general-applications#443
> Revert "vulnerability fix"

- .github/PULL_REQUEST_TEMPLATE.md
n/a
Add New checklists for PR review
```
[ ] Yes
[x] No
```
> Add new checklist for PR review

- bin/variables/load-staging-environment-variables.sh
https://tools.hmcts.net/jira/browse/CIV-4462
fix master
```
[ ] Yes
[ ] No
```
> CIV-4462 update SERVICE_AUTH_PROVIDER_API_BASE_URL

- bin/variables/load-staging-environment-variables.sh
- charts/civil-general-applications/values.aat.template.yaml
> Fix master

- Jenkinsfile_CNP
- bin/variables/load-staging-environment-variables.sh
- charts/civil-general-applications/values.aat.template.yaml
- charts/civil-general-applications/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/CIV-4462
Fix master pipeline
```
[ ] Yes
[ ] No
```
> Fix master pipeline

- charts/civil-general-applications/values.aat.template.yaml
- charts/civil-general-applications/values.preview.template.yaml
> added postgres image

- Jenkinsfile_CNP
> fix pipeline

- build.gradle
- config/owasp/suppressions.xml
> solve CVE-2022-25647

- Jenkinsfile_CNP
- build.gradle
- charts/civil-general-applications/Chart.yaml
- charts/civil-general-applications/values.aat.template.yaml
- charts/civil-general-applications/values.preview.template.yaml
- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/tasks/CreateApplicationTaskHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/model/CaseData.java
- src/main/java/uk/gov/hmcts/reform/civil/service/ParentCaseUpdateHelper.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/businessprocess/EndGeneralAppBusinessProcessCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/tasks/CreateApplicationTaskHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataBuilder.java
> Dependentbotsmerge

- src/main/java/uk/gov/hmcts/reform/civil/enums/CaseState.java
https://tools.hmcts.net/jira/browse/CIV-5012
add 2 parent states
screen shots are in ticket
```
[x] Yes
[ ] No
```
> CIV-5012 add 2 new parent states

- src/main/java/uk/gov/hmcts/reform/civil/service/ParentCaseUpdateHelper.java
- src/test/java/uk/gov/hmcts/reform/civil/service/ParentCaseUpdateHelperTest.java
Reverts hmcts/civil-general-applications#585
> Revert "CIV-5085 fix update ga status with visible to resp sol; add test cases"

- src/main/java/uk/gov/hmcts/reform/civil/service/DeadlinesCalculator.java
- src/test/java/uk/gov/hmcts/reform/civil/service/DeadlinesCalculatorTest.java
https://tools.hmcts.net/jira/browse/CIV-4981
Refactor notification deadline calc. to add extra day for each holiday if it's present in total period
```
[ ] Yes
[ ] No
```
> CIV-4981 Refactor notification deadline calc.

- bin/add-roles.sh
https://tools.hmcts.net/jira/browse/CIV-5223
new access-profile for PBAv3
```
[ ] Yes
[ x] No
```
> access profile "payment-access" added

- .gitignore
- infrastructure/main.tf
CIV-5385 
Add Content Type and Source to secret
```
[ ] Yes
[ x ] No
```
> CIV-5385 - Add Content Type and Source to secret

- bin/add-roles.sh
- build.gradle
> Dependentbotmerge

- Jenkinsfile_CNP
- build.gradle
- charts/civil-general-applications/values.aat.template.yaml
- charts/civil-general-applications/values.preview.template.yaml
- config/owasp/suppressions.xml
> changes for key and cve

- build.gradle
- charts/civil-general-applications/values.preview.template.yaml
> Dependabotlatest

- build.gradle
- charts/civil-general-applications/Chart.yaml
> Dependabot p rcombine

- charts/civil-general-applications/Chart.yaml
- charts/civil-general-applications/values.aat.template.yaml
- charts/civil-general-applications/values.preview.template.yaml
Removed user-profile-importer
Changed user-profile API to use AAT instance.
- [ x] commit messages are meaningful and follow good commit message guidelines
https://tools.hmcts.net/jira/browse/CIV-5969
Removed user-profile-importer 
Changed user-profile API to use AAT instance. Saves a pod per pr being spun up.
Increase ccd-data-store cpu
```
[ ] Yes
[x ] No
```
> CIV-5969 User profile dependencies

- charts/civil-general-applications/Chart.yaml
- charts/civil-general-applications/values.aat.template.yaml
- charts/civil-general-applications/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/CIV-5968
Move postgresql implementation for GA to chart-java instead of pulling from external always. Should reduce failure probability and also maintenance.
```
[ ] Yes
[ ] No
```
> CIV-5968 Move Postgresql to chart-java

- build.gradle
> Dependabotdecember2

- src/main/java/uk/gov/hmcts/reform/civil/controllers/testingsupport/TestingSupportController.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/tasks/CheckStayOrderDeadlineEndTaskHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/tasks/GAJudgeRevisitTaskHandler.java
> Civ 6338 1

- Jenkinsfile_CNP
- build.gradle
- charts/civil-general-applications/Chart.yaml
> Dependabotdec13th

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/service/JudicialDecisionHelper.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/JudicialDecisionHelperTest.java
Reverts hmcts/civil-general-applications#728
> CIV-6286 Refactor Judicial Recital text

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-6345
Remove 7 day paragraph from order field
Scenario 1: Make Order - Approve or edit
Scenario 2: Make Order - Dismiss
Scenario 3: Make Order - Give directions
Scenario 4: List for Hearing (Directions in relation to hearing field)
Scenario 5: Order for written representations - Sequential
Scenario 6: Order for written representations - Concurrent
```
[ ] Yes
[ ] No
```
> CIV-6345 Remove 7 day paragraph from order field

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CIV-6398
Remove CVE
```
[ ] Yes
[ ] No
```
> CIV-6398 Remove CVE

- build.gradle
> Dependencybotdec19

- Jenkinsfile_CNP
> Remove nonprod c UI

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToApplicationHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/service/GeneralAppLocationRefDataService.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToApplicationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/GeneralAppLocationRefDataServiceTest.java
https://tools.hmcts.net/jira/browse/CIV-6296
Update list of courts in drop down when Judge lists for hearing as same as list in SDO. Remove the filter to filter out Scotland in GA
Civil, GA
CIV-6296
```
[ ] Yes
[ ] No
```
> CIV-6296 Update list of courts in drop down when judge lists for hearing

- Jenkinsfile_CNP
> Revert Changes CUI

- build.gradle
> Dependabotjan4

- build.gradle
> Dependabot

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-6682
Refactor hearing screen applicant and respondent preference text
```
[ ] Yes
[ ] No
```
> CIV-6682 Refactor hearing screen appln and resp preference wording

- build.gradle
- charts/civil-general-applications/Chart.yaml
> Dependabotjan30

- build.gradle
- charts/civil-general-applications/values.aat.template.yaml
- charts/civil-general-applications/values.preview.template.yaml
> Dependabotfeb3

- src/main/java/uk/gov/hmcts/reform/civil/controllers/testingsupport/TestingSupportController.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/HearingScheduledEventCallbackHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/HearingScheduledEventCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-7003
Confirmation message on submission corrected
```
[ ] Yes
[x ] No
```
> CIV-7003 updated confirmation message on submission of application

- Jenkinsfile_CNP
> Point GA CCD Branch to Master

- .github/CODEOWNERS
- .github/workflows/main.yml
CIV-5433
Add title format validation
Add CODEOWNERS file
```
[ ] Yes
[ x ] No
```
> CIV-5433 - Add Title validation and CodeOwners

- Jenkinsfile_CNP
- build.gradle
> CIV-0000 fix yarn lock issue

- .github/dependabot.yml
- .github/renovate.json
- Dockerfile
https://tools.hmcts.net/jira/browse/CIV-7083
Dependabot is replaced by Renovate
```
[ ] Yes
[x] No
```
> CIV-7083 Dependabot replaced by Renovate

- infrastructure/main.tf
> CIV-7072 changes to introduce app connection string

- bin/add-roles.sh
> CIV-0000 Update add-roles.sh

- Jenkinsfile_CNP
- config/owasp/suppressions.xml
> CIV-7014 ga-ccd revert o master

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/InitiateGeneralApplicationHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/InitiateGeneralApplicationHandlerTest.java
- [ x] commit messages are meaningful and follow good commit message guidelines
https://tools.hmcts.net/jira/browse/CIV-7014
Modified confirmation body message at the time successful initiation of general application.
```
[ ] Yes
[x ] No
```
> CIV-7014 Modified confirmation body message

- Jenkinsfile_CNP
- charts/civil-general-applications/values.template.yaml
> CIV-0000 ways to payfix

- Jenkinsfile_CNP
- charts/civil-general-applications/values.template.yaml
> CIV-0000 fixpipelinebrokenbycivilservice

- Jenkinsfile_CNP
- build.gradle
- charts/civil-general-applications/Chart.yaml
> CIV-7508 further-changes necessary changes. update civil service chart

- build.gradle
- config/owasp/suppressions.xml
> CIV-0000 cve cleanup

- build.gradle
- config/owasp/suppressions.xml
> CIV-0000 fix cve

- charts/civil-general-applications/Chart.yaml
> CIV-0000 ccd chart update

- Jenkinsfile_CNP
- src/main/java/uk/gov/hmcts/reform/civil/controllers/testingsupport/TestingSupportController.java
https://tools.hmcts.net/jira/browse/CIV-7560
Refactor GA Business process testing support to accommodate multiple general application. 
```
[ ] Yes
[ ] No
```
> CIV-7560 Refactor GA Business process for Multiple GA

- config/owasp/suppressions.xml
N/A
Temporary suppression of CVE-2023-20860 as it doesn't have a fix yet.
```
[ ] Yes
[x] No
```
> CIV-TASK Temporarily suppress CVE-2023-20860

- charts/civil-general-applications/values.aat.template.yaml
Increase memery of data store to 8 GB
```
[ ] Yes
[ ] No
```
> CIV-0000 Increased memory

- Jenkinsfile_CNP
> CIV-0000 Update Jenkinsfile_CNP to point gaccd camunda to master

- build.gradle
- config/checkstyle/checkstyle.xml
- src/main/java/uk/gov/hmcts/reform/civil/callback/CallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/callback/CallbackHandlerFactory.java
- src/main/java/uk/gov/hmcts/reform/civil/callback/CaseEvent.java
- src/main/java/uk/gov/hmcts/reform/civil/controllers/CallbackController.java
- src/main/java/uk/gov/hmcts/reform/civil/controllers/testingsupport/UpdateCaseDataController.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/caseassignment/AssignCaseToUserCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GenerateHearingNoticeDocumentCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GeneratePDFDocumentCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/fee/AdditionalFeeValueCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/fee/ValidateFeeCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/payment/AdditionalPaymentsReferenceCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/payment/PaymentServiceRequestHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/HearingScheduledEventCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/finalorder/AssistedOrderFormGenerator.java
- src/main/java/uk/gov/hmcts/reform/civil/utils/JudicialDecisionNotificationUtil.java
- src/test/java/uk/gov/hmcts/reform/civil/callback/CallbackHandlerFactoryTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GenerateHearingNoticeDocumentCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GeneratePDFDocumentCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/fee/AdditionalFeeValueCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/fee/ValidateFeeCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/payment/AdditionalPaymentsReferenceCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/payment/CreateServiceRequestHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/HearingScheduledEventCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialFinalDecisionHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/docmosis/finalorder/FreeFormOrderGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/docmosis/hearingorder/HearingFormGeneratorTest.java
https://tools.hmcts.net/jira/browse/CIV-7675
Fix GA code smell blocker & critical in Sonarcloud
```
[ ] Yes
[ ] No
```
> CIV-7675 Fix GA code smell blocker & critical in Sonarcloud

- build.gradle
- config/checkstyle/checkstyle.xml
- src/main/java/uk/gov/hmcts/reform/civil/callback/CallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/callback/CallbackHandlerFactory.java
- src/main/java/uk/gov/hmcts/reform/civil/callback/CaseEvent.java
- src/main/java/uk/gov/hmcts/reform/civil/controllers/CallbackController.java
- src/main/java/uk/gov/hmcts/reform/civil/controllers/testingsupport/UpdateCaseDataController.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/caseassignment/AssignCaseToUserCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GenerateHearingNoticeDocumentCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GeneratePDFDocumentCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/fee/AdditionalFeeValueCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/fee/ValidateFeeCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/payment/AdditionalPaymentsReferenceCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/payment/PaymentServiceRequestHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/HearingScheduledEventCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/finalorder/AssistedOrderFormGenerator.java
- src/main/java/uk/gov/hmcts/reform/civil/utils/JudicialDecisionNotificationUtil.java
- src/test/java/uk/gov/hmcts/reform/civil/callback/CallbackHandlerFactoryTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GenerateHearingNoticeDocumentCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GeneratePDFDocumentCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/fee/AdditionalFeeValueCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/fee/ValidateFeeCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/payment/AdditionalPaymentsReferenceCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/payment/CreateServiceRequestHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/HearingScheduledEventCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialFinalDecisionHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/docmosis/finalorder/FreeFormOrderGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/docmosis/hearingorder/HearingFormGeneratorTest.java
Reverts hmcts/civil-general-applications#978
> Revert "CIV-7675 Fix GA code smell blocker & critical in Sonarcloud"

- build.gradle
- config/checkstyle/checkstyle.xml
- src/main/java/uk/gov/hmcts/reform/civil/callback/CallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/callback/CallbackHandlerFactory.java
- src/main/java/uk/gov/hmcts/reform/civil/callback/CaseEvent.java
- src/main/java/uk/gov/hmcts/reform/civil/controllers/CallbackController.java
- src/main/java/uk/gov/hmcts/reform/civil/controllers/testingsupport/UpdateCaseDataController.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/caseassignment/AssignCaseToUserCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GenerateHearingNoticeDocumentCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GeneratePDFDocumentCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/fee/AdditionalFeeValueCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/fee/ValidateFeeCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/payment/AdditionalPaymentsReferenceCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/payment/PaymentServiceRequestHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/HearingScheduledEventCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/finalorder/AssistedOrderFormGenerator.java
- src/main/java/uk/gov/hmcts/reform/civil/utils/JudicialDecisionNotificationUtil.java
- src/test/java/uk/gov/hmcts/reform/civil/callback/CallbackHandlerFactoryTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GenerateHearingNoticeDocumentCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GeneratePDFDocumentCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/fee/AdditionalFeeValueCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/fee/ValidateFeeCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/payment/AdditionalPaymentsReferenceCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/payment/CreateServiceRequestHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/HearingScheduledEventCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialFinalDecisionHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/docmosis/finalorder/FreeFormOrderGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/docmosis/hearingorder/HearingFormGeneratorTest.java
https://tools.hmcts.net/jira/browse/CIV-7675
```
[ ] Yes
[ ] No
```
> CIV-7675 Fix Sonar bug

- src/main/java/uk/gov/hmcts/reform/civil/model/CaseData.java
- src/main/java/uk/gov/hmcts/reform/civil/model/genapplication/GeneralApplication.java
https://tools.hmcts.net/jira/browse/CIV-6245
Applicant Name appears in a section at the top of the summary page and is visible by all parties, staff and Judges
https://github.com/hmcts/civil-general-apps-ccd-definition/pull/673
```
[ ] Yes
[x] No
```
> CIV-6245 Allow Judges to see who has made the application

- Jenkinsfile_CNP
> CIV-0000 Pointing ga ccd to feat/CIV-6245

- build.gradle
- config/owasp/suppressions.xml
> CIV-0000 remove suppressions as part of springboot upgrade

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/UpdateGaLocationCallbackHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/UpdateGaLocationCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-8283
Location Name on general applications are not getting updated properly when main claim moved to after SDO state
```
[ ] Yes …
```
> CIV-8283 Regression bug locationName is not getting updated in GA after SDO

- src/main/java/uk/gov/hmcts/reform/civil/enums/dq/GeneralApplicationTypes.java
https://tools.hmcts.net/jira/browse/CIV-8117
Application type: Settle or Discontinue by consent
```
[ ] Yes
[x] No
```
> CIV-8117 Settle or Discontinue by consent

- build.gradle
> CIV-0000 changing to latest spring security

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- build.gradle
> CIV-0000 nightly fix changes

- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/hearingorder/HearingFormGenerator.java
- src/test/java/uk/gov/hmcts/reform/civil/service/docmosis/hearingorder/HearingFormGeneratorTest.java
> CIV-8414 changing in dateformatter for hearing form generator

- Jenkinsfile_CNP
> CIV-0000 adding exclusions for shuttered.json

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/ReferToJudgeOrLegalAdvisorHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/ReferToJudgeOrLegalAdvisorHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-7930
Updated logic so that user/caseworker can "Refer_to_judge" after SDO. 
https://github.com/hmcts/civil-general-apps-ccd-definition/pull/706
```
[ ] Yes
[ ] No
```
> CIV-7930 updated logic After SDO

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/fee/AdditionalFeeValueCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/fee/ValidateFeeCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/service/GeneralAppFeesService.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/fee/AdditionalFeeValueCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/fee/ValidateFeeCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/GeneralAppFeesServiceTest.java
https://tools.hmcts.net/jira/browse/CIV-5226
ga fees
https://github.com/hmcts/civil-general-apps-ccd-definition/pull/725
```
[ ] Yes
[x] No
```
> CIV-5226 fees

- charts/civil-general-applications/values.aat.template.yaml
- charts/civil-general-applications/values.preview.template.yaml
> CIV-0000 switch off stitching

- src/main/java/uk/gov/hmcts/reform/civil/service/PaymentRequestUpdateCallbackService.java
- src/main/java/uk/gov/hmcts/reform/civil/service/StateGeneratorService.java
- src/test/java/uk/gov/hmcts/reform/civil/service/PaymentRequestUpdateCallbackServiceTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/StateGeneratorServiceTest.java
https://tools.hmcts.net/jira/browse/CIV-8533
- Added logic for the application going to APPLICATION_SUBMITTED_AWAITING_JUDICIAL_DECISION after additional payment is made. 
- Added logic for not sending emails When after additonal payment for consent orders
```
[ ] Yes
[ ] No
```
> CIV-8533 Consent Order After additional payment

- .github/renovate.json
> CIV-0000 Change renovate timings

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/ApproveConsentOrderCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/tasks/CheckStayOrderDeadlineEndTaskHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/model/genapplication/GAApproveConsentOrder.java
- src/main/java/uk/gov/hmcts/reform/civil/service/search/CaseStateSearchService.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/tasks/CheckStayOrderDeadlineEndTaskHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataBuilder.java
- src/test/java/uk/gov/hmcts/reform/civil/service/search/CaseStateSearchServiceTest.java
https://tools.hmcts.net/jira/browse/CIV-8609
- Added new variable isOrderProcessedByStayScheduler to GAApproveConsentOrder
-  Refactor and added logic for consentORder filtering in CheckStayOrderDeadlineEndTaskHandler.java
- Updated search criteria in CaseStateSearchService
```
[ ] Yes
[ ] No
```
> CIV-8609 Consent Order- Stay the Claim

- build.gradle
> CIV-0000 upgrade spring boot to latest fix cve

- src/main/java/uk/gov/hmcts/reform/civil/handler/tasks/CreateApplicationTaskHandler.java
https://tools.hmcts.net/jira/browse/CIV-9132
Refactor Respondent one orgid
```
[ ] Yes
[ ] No
```
> CIV-9132 Refactor respondent one orgid

- Jenkinsfile_CNP
> CIV-0000 Pointing to master

- build.gradle
- config/owasp/suppressions.xml
> CIV-0000 increment jackson datatype version

- src/main/java/uk/gov/hmcts/reform/civil/handler/tasks/CaseEventTaskHandler.java
https://tools.hmcts.net/jira/browse/CIV-9298
remove unused parameter
```
[ ] Yes
[x] No
```
> CIV-9298 remove unused parameter

- build.gradle
- config/owasp/suppressions.xml
> CIV-0000 updated jars

- Jenkinsfile_CNP
> CIV-0000 Update Jenkinsfile_CNP SETTING MASTER

- Jenkinsfile_CNP
- bin/add-roles.sh
https://tools.hmcts.net/jira/browse/CIV-9513
```
[ ] Yes
[ ] No
```
> CIV-9513 Removed exclusion for cui nonprod

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GenerateApplicationDraftCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/service/ParentCaseUpdateHelper.java
- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/applicationdraft/GeneralApplicationDraftGenerator.java
- src/main/java/uk/gov/hmcts/reform/civil/utils/JudicialDecisionNotificationUtil.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GenerateApplicationDraftCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/ParentCaseUpdateHelperTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/docmosis/applicationdraft/GeneralApplicationDraftGeneratorTest.java
https://tools.hmcts.net/jira/browse/CIV-9383
```
[ ] Yes
[ ] No
```
> CIV-9383 Generate Draft document for zero fee

- Jenkinsfile_CNP
- src/main/java/uk/gov/hmcts/reform/civil/handler/tasks/FailedEventEmitterHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/service/tasklisteners/FailedEventEmitterExternalTaskListener.java
https://tools.hmcts.net/jira/browse/CIV-9598
```
[ ] Yes
[ ] No
```
> CIV-9598 updated execution condition

- bin/add-roles.sh
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CIV-5339
added new profile
```
[ ] Yes
[x] No
```
> CIV-5339 - Release 2 - LIP v LIP Update Access Profile

- .github/workflows/main.yml
CIV-00000 Changing naming pattern for branches
```
[ ] Yes
[x ] No
```
> CIV-00000 Modified naming pattern for branches

- build.gradle
- config/owasp/suppressions.xml
> CIV-0000 update spring boot

- src/main/java/uk/gov/hmcts/reform/civil/config/SecurityConfiguration.java
> CIV-0000 temp S2S change

- src/main/java/uk/gov/hmcts/reform/civil/enums/dq/GAJudgeDecisionOption.java
https://tools.hmcts.net/jira/browse/CIV-10069
Update judicial make decision options
```
[ ] Yes
[ ] No
```
> CIV-10069 Refactor Judicial options

- Jenkinsfile_CNP
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/businessprocess/EndGeneralAppBusinessProcessCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/tasks/CreateApplicationTaskHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/service/ParentCaseUpdateHelper.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/businessprocess/EndGeneralAppBusinessProcessCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/tasks/CreateApplicationTaskHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataBuilder.java
- src/test/java/uk/gov/hmcts/reform/civil/service/ParentCaseUpdateHelperTest.java
https://tools.hmcts.net/jira/browse/CIV-9933
Respondents should not be able to see applications until they have been paid for, and should not see Without Notice applications until the Judge uncloaks when making a decision or sends the …
> CIV-9933 Applications added to main case collection after payment

- Jenkinsfile_CNP
Reverting ga-ccd branch back to master after merging CIV-9933
```
[ ] Yes
[ x] No
```
> CIV-0000 reverting ga-ccd branch back to master

- Jenkinsfile_CNP
- build.gradle
- src/integrationTest/java/uk/gov/hmcts/reform/civil/controllers/BaseIntegrationTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/civil/controllers/PaymentRequestUpdateCallbackControllerTest.java
- src/main/java/uk/gov/hmcts/reform/civil/config/SecurityConfiguration.java
- src/main/java/uk/gov/hmcts/reform/civil/controllers/PaymentRequestUpdateCallbackController.java
- src/main/java/uk/gov/hmcts/reform/civil/service/AuthorisationService.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/civil/service/AuthorisationServiceTest.java
initial commit with the relevant changes
- introduced authorisation service
- changes on payment call back service to check and throw relevant exception
```
[ ] Yes
[ ] No
```
> CIV-10448 S2S refactor

- charts/civil-general-applications/Chart.yaml
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToApplicationHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/model/CaseData.java
- src/main/java/uk/gov/hmcts/reform/civil/model/docmosis/GADraftForm.java
- src/main/java/uk/gov/hmcts/reform/civil/model/genapplication/GARespondentResponse.java
- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/applicationdraft/GeneralApplicationDraftGenerator.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToApplicationHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-9750
not agree respond
```
[ ] Yes
[x] No
```
> CIV-9750 not agree respond

- Jenkinsfile_CNP
> CIV-0000 revert PR-1117

- Jenkinsfile_CNP
Updated ga-ccd back to master
```
[ ] Yes
[x ] No
```
> CIV-0000 updated back to master

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/businessprocess/EndGeneralAppBusinessProcessCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToJudgeAddlnInfoHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToWrittenRepresentationHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/ResponseToJudgeDirectionsOrder.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/tasks/StartGeneralApplicationBusinessProcessTaskHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/businessprocess/EndGeneralAppBusinessProcessCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/businessprocess/StartGeneralApplicationBusinessProcessCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToJudgeAddlnInfoHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondWrittenRepresentationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/ResponseToJudgeDirectionsOrderHanderTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/tasks/StartGeneralApplicationBusinessProcessTaskHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataBuilder.java
https://tools.hmcts.net/jira/browse/CIV-9804
To Avoid 403 Forbidden error while uploading a document from general application, added a new bpmn flows for Respond to Judge Directions, Respond to Judge Additional Info, Respond to Judge …
> CIV-9804 Added new BPMN flows for Response to Judge Directions for uploading a document to Main case

- Jenkinsfile_CNP
> CIV-10423 ga ccd point to master

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialFinalDecisionHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialFinalDecisionHandlerTest.java
> CIV-0000 add commas

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialFinalDecisionHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/model/common/DynamicListElement.java
- src/main/java/uk/gov/hmcts/reform/civil/model/genapplication/finalorder/AssistedOrderDateHeard.java
- src/main/java/uk/gov/hmcts/reform/civil/model/genapplication/finalorder/AssistedOrderFurtherHearingDetails.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/businessprocess/MoveToJudicialDecisionStateEventCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GenerateApplicationDraftCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/HearingScheduledEventCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialFinalDecisionHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/sampledata/CaseDataBuilder.java
- src/test/java/uk/gov/hmcts/reform/civil/service/JudicialDecisionHelperTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/docmosis/applicationdraft/GeneralApplicationDraftGeneratorTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/docmosis/finalorder/AssistedOrderFormGeneratorTest.java
- [ x] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)
- [ x] Screenshot attached for the Evidence of manual testing
- [ x] Functional, Smoke and API tests have been run locally
- [ x] Full gradle build and run tests with coverage have been completed (if needed)
https://tools.hmcts.net/jira/browse/CIV-10426
```
[ ] Yes
[x ] No
```
> CIV-10426 Order Updates - Assisted Order for Applications - Further Hearing

- src/main/java/uk/gov/hmcts/reform/civil/model/docmosis/FreeFormOrder.java
- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/finalorder/FreeFormOrderGenerator.java
- src/test/java/uk/gov/hmcts/reform/civil/service/docmosis/finalorder/FreeFormOrderGeneratorTest.java
[Application Orders - Free Form - Output](https://tools.hmcts.net/jira/browse/CIV-9787)
Application Orders - Free Form - document
```
[ ] Yes
[x] No
```
> CIV-9787 Application Orders - Free Form

- Jenkinsfile_CNP
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/InitiateGeneralApplicationHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/InitiateGeneralApplicationHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-10646
application text change
https://github.com/hmcts/civil-general-apps-ccd-definition/pull/877
```
[ ] Yes
[x] No
```
> CIV-10646 application text change

- src/main/java/uk/gov/hmcts/reform/civil/enums/dq/GeneralApplicationTypes.java
- src/main/java/uk/gov/hmcts/reform/civil/service/GeneralAppFeesService.java
- src/test/java/uk/gov/hmcts/reform/civil/service/GeneralAppFeesServiceTest.java
https://tools.hmcts.net/jira/browse/CIV-10231
1. Update any reference to Settle or Discontinue by consent to Settle by consent including the error messages
2. On the Is there a hearing screen, update the question asked to be: Is the application for an adjournment of a hearing which is at least 14 days away?
and if yes date field reads: Please provide the hearing dates
Help text to be updated to: If there is is more than one hearing, please provide the date of the earliest hearing
```
[ ] Yes
[ ] No
```
> CIV-10231 Update Application Type Name

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-10664
Update Judge Recital text for without notice and with notice application
```
[ ] Yes
[ ] No
```
> CIV-10664 Update Judge Recital Text

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-10664
Add the missing word in judge recital text
```
[ ] Yes
[ ] No
```
> CIV-10664 Add missing word in recital text

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-10926
Update written rep label
```
[ ] Yes
[ ] No
```
> CIV-10926 Update written rep label

- charts/civil-general-applications/Chart.yaml
> CIV-0000 upgrading to java 5.0.0

- Jenkinsfile_CNP
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/fee/ValidateFeeCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/model/Fee.java
- src/test/java/uk/gov/hmcts/reform/civil/model/FeeTest.java
> DTSCCI-258 Add logging for fee comparison

- src/main/java/uk/gov/hmcts/reform/civil/utils/GaForLipService.java
> CIV-14006 Add null check

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/caseassignment/AssignCaseToUserCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/launchdarkly/FeatureToggleService.java
- src/main/java/uk/gov/hmcts/reform/civil/service/AssignCaseToResopondentSolHelper.java
- src/main/java/uk/gov/hmcts/reform/civil/service/GaForLipService.java
- src/main/java/uk/gov/hmcts/reform/civil/service/SolicitorEmailValidation.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/payment/ModifyStateAfterAdditionalFeeReceivedCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/caseassignment/AssignCaseToUserHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/launchdarkly/FeatureToggleServiceTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/SolicitorEmailValidationTest.java
https://tools.hmcts.net/jira/browse/CIV-14006
```
[ ] Yes
[ ] No
```
> CIV-14006 Add featureflage for GA for LIPS

- src/main/java/uk/gov/hmcts/reform/civil/config/SecurityConfiguration.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/tasks/CreateApplicationTaskHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/model/genapplication/GeneralApplication.java
https://tools.hmcts.net/jira/browse/CIV-14083
Create GA for LiP
```
[ ] Yes
[x] No
```
> CIV-9456 Create GA for LiP

- src/integrationTest/java/uk/gov/hmcts/reform/civil/controllers/FeesPaymentControllerTest.java
- src/main/java/uk/gov/hmcts/reform/civil/service/FeesPaymentService.java
- src/test/java/uk/gov/hmcts/reform/civil/service/FeesPaymentServiceTest.java
https://tools.hmcts.net/jira/browse/CIV-9465
Set up Lip pay for application
```
[ ] Yes
[x] No
```
> CIV-9465 LiP Pay for Application

- src/main/java/uk/gov/hmcts/reform/civil/client/DocmosisApiClient.java
- src/main/java/uk/gov/hmcts/reform/civil/client/FeesApiClient.java
- src/main/java/uk/gov/hmcts/reform/civil/client/OrganisationApi.java
- src/main/java/uk/gov/hmcts/reform/civil/controllers/testingsupport/AssignCaseSupportController.java
- src/main/java/uk/gov/hmcts/reform/civil/controllers/testingsupport/TestingSupportController.java
- src/main/java/uk/gov/hmcts/reform/civil/launchdarkly/OnBoardingOrganisationControlService.java
- src/main/java/uk/gov/hmcts/reform/civil/model/ContactInformation.java
- src/main/java/uk/gov/hmcts/reform/civil/model/DxAddress.java
- src/main/java/uk/gov/hmcts/reform/civil/model/Organisation.java
- src/main/java/uk/gov/hmcts/reform/civil/model/SuperUser.java
- src/main/java/uk/gov/hmcts/reform/civil/service/GeneralAppFeesService.java
- src/main/java/uk/gov/hmcts/reform/civil/service/OrganisationService.java
- src/main/java/uk/gov/hmcts/reform/civil/service/PaymentsService.java
- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/DocumentGeneratorService.java
- src/test/java/uk/gov/hmcts/reform/civil/launchdarkly/OnBoardingOrganisationControlServiceTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/GeneralAppFeesServiceTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/GeneralAppLocationRefDataServiceTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/OrganisationServiceTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/PaymentsServiceTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/docmosis/DocumentGeneratorServiceTest.java
…ovided to transfer the contract responsibility
https://tools.hmcts.net/jira/browse/DTSCCI-375
```
[ ] Yes
[ ] No
```
> DTSCCI-377 removing local apis when there are external lib

- src/main/java/uk/gov/hmcts/reform/civil/client/LocationReferenceDataApiClient.java
- src/main/java/uk/gov/hmcts/reform/civil/service/GeneralAppLocationRefDataService.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/civil/service/GeneralAppLocationRefDataServiceTest.java
https://tools.hmcts.net/jira/browse/DTSCCI-375
```
[ ] Yes
[ ] No
```
> DTSCCI-375 replace restTemplate with ref data client

- src/contractTest/java/uk/gov/hmcts/reform/civil/FeesLookupApiConsumerTest.java
https://tools.hmcts.net/jira/browse/DTSCCI-379
```
[ ] Yes
[ ] No
```
> DTSCCI-379 refactored fees contract test

- charts/civil-general-applications/values.preview.template.yaml
DTSCCI-490
remove deprecated property volume lib
```
[ ] Yes
[ ] No
```
> DTSCCI-490 remove deprecated property volume lib

- bin/pull-latest-release-asset.sh
- bin/utils/idam-lease-user-token.sh
> CIV-0000 : Fix docker rate limiter issue

- charts/civil-general-applications/Chart.yaml
- charts/civil-general-applications/values.yaml
DTSCCI-490
map os postcode key to ordnance survey api key
as used in AAT.
```
[ ] Yes
[ ] No
```
> DTSCCI-490 map os postcode key to ordnance survey api key

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/FeePaymentOutcomeHWFCallBackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/FullRemissionHWFCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/model/genapplication/HelpWithFeesDetails.java
- src/main/java/uk/gov/hmcts/reform/civil/utils/HwFFeeTypeService.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/FeePaymentOutcomeHWFCallBackHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-14036
Populate and Store HwF data Fields to display in Application CaseType Tab
- Set HwF type
- Add new fields to store PBA details and HWF reference for HwF payment and HwF Additional Payment
https://github.com/hmcts/civil-general-apps-ccd-definition/pull/1208
```
[ ] Yes
[ ] No
```
> CIV-14036 Populate HWF Data

- src/main/java/uk/gov/hmcts/reform/civil/controllers/CasesController.java
https://tools.hmcts.net/jira/browse/CIV-14960
adding parentClaimantIsApplicant to getCaseApplications so that it can be used in cui isApplicationVisibleToRespondent 
```
[ ] Yes
[ ] No
```
> CIV-14960  Updating getCaseApplications

- src/main/java/uk/gov/hmcts/reform/civil/controllers/CasesController.java
https://tools.hmcts.net/jira/browse/CIV-13999
Upload additional documents
```
[ ] Yes
[ ] No
```
> CIV-13999 Upload additional documents

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-9487
Handle hearing duration estimate not provided
```
[ ] Yes
[x] No
```
> CIV-9487 Handle hearing duration estimate not provided

- src/main/java/uk/gov/hmcts/reform/civil/service/ParentCaseUpdateHelper.java
- [ x] Screenshot attached for the Evidence of manual testing
https://tools.hmcts.net/jira/browse/CIV-14404
https://tools.hmcts.net/jira/browse/CIV-15199
```
[ ] Yes
[ ] No
```
> CIV-15199 removed condition to make ParentClaimantIsApplicant casefield null 

- src/main/java/uk/gov/hmcts/reform/civil/service/ParentCaseUpdateHelper.java
DTSCCI-816
fix npe on multiple Ga's - when multiple ga's created and previous ga hasn't finished- it throws npe as it can't find another added ga case refer as it hasn't linked yet.
```
[ ] Yes
[ ] No
```
> DTSCCI-816 fix npe on multiple ga apps

- infrastructure/providers.tf
- infrastructure/state.tf
> CIV-00000 skip_provider_registration to true

- src/main/java/uk/gov/hmcts/reform/civil/service/DashboardNotificationsParamsMapper.java
- src/test/java/uk/gov/hmcts/reform/civil/service/DashboardNotificationsParamsMapperTest.java
https://tools.hmcts.net/jira/browse/CIV-15174
Add parameter values for notification deadlines
```
[ ] Yes
[x] No
```
> CIV-15174 Add parameter values for notification deadlines

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialFinalDecisionHandler.java
put bilingualHint behind feature toggle
```
[ ] Yes
[x] No
```
> CIV-0000 fix bilingualHint behind feature toggle

- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/applicationdraft/GeneralApplicationDraftGenerator.java
- src/test/java/uk/gov/hmcts/reform/civil/service/docmosis/applicationdraft/GeneralApplicationDraftGeneratorTest.java
https://tools.hmcts.net/jira/browse/CIV-14289
Set iswithnotice to yes when judge uncloaks the application
```
[ ] Yes
[ ] No
```
> CIV-14289 refactor iswithnotice mapping when judge uncloaks

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/FeePaymentOutcomeHWFCallBackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/model/CaseData.java
- src/main/java/uk/gov/hmcts/reform/civil/model/genapplication/FeePaymentOutcomeDetails.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/FeePaymentOutcomeHWFCallBackHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-15457
```
[ ] Yes
[ ] No
```
> CIV-15457 Update full remission check

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/fee/ValidateFeeCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/payment/PaymentServiceRequestHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/fee/ValidateFeeCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/payment/CreateServiceRequestHandlerTest.java
- [X ] commit messages are meaningful and follow good commit message guidelines
- [X ] README and other documentation has been updated / added (if needed)
- [X ] tests have been updated / new tests has been added (if needed)
- [X ] Screenshot attached for the Evidence of manual testing
- [X ] Functional, Smoke and API tests have been run locally
- [X ] Full gradle build and run tests with coverage have been completed (if needed)
https://tools.hmcts.net/jira/browse/CIV-15543
```
[ ] Yes
[ X] No
```
> CIV-15543 REMOVED FEE VALIDATION FOR LIP CASES

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/ApplicationSubmittedDashboardNotificationHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/ApplicationSubmittedDashboardNotificationHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-15496
Show GA submitted notification when HWF
```
[ ] Yes
[x] No
```
> CIV-15496 Show GA submitted notification when HWF

- build.gradle
…ns nightly
```
[ ] Yes
[ ] No
```
> DTSCCI-000 - Make nightly tests run first in civil-general-applications nightly

- Jenkinsfile_CNP
- charts/civil-general-applications/Chart.yaml
- charts/civil-general-applications/values.yaml
https://tools.hmcts.net/jira/browse/CIV-15113
Add EM_CCD_ORCHESTRATOR_URL env var
```
[ ] Yes
[x] No
```
> CIV-15113 Add EM_CCD_ORCHESTRATOR_URL env var

- src/main/java/uk/gov/hmcts/reform/civil/service/ParentCaseUpdateHelper.java
- src/test/java/uk/gov/hmcts/reform/civil/service/ParentCaseUpdateHelperTest.java
https://tools.hmcts.net/jira/browse/CIV-15836
fix findGaCreator for Lip Resp
```
[ ] Yes
[x] No
```
> CIV-15836 fix findGaCreator for Lip Resp

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToApplicationHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToApplicationHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-15773
Display response preferred location
```
[ ] Yes
[x] No
```
> CIV-15773 Display response preferred location

- src/main/java/uk/gov/hmcts/reform/civil/controllers/CasesController.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandler.java
https://tools.hmcts.net/jira/browse/CIV-15802
```
[ ] Yes
[ ] No
```
> CIV-15802 Update CasesController GA CUI

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/UploadAdditionalDocumentsCallbackHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/UploadAdditionalDocumentsCallbackHandlerTest.java
- [ x] commit messages are meaningful and follow good commit message guidelines
https://tools.hmcts.net/jira/browse/CIV-15904
dashboard notification missing for uploading additional docs
```
[ ] Yes
[ x] No
```
> CIV-15904 dashboard notification missing for uploading additional docs

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/FeePaymentOutcomeHWFCallBackHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/FeePaymentOutcomeHWFCallBackHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-15515
HwF screen prepopulated value
```
[ ] Yes
[x] No
```
> CIV-15515 HwF screen prepopulated value

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/ApplicationIssuedFeeRequiredHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/ApplicationIssuedFeeRequiredHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-15544
Avoid creating dashboard notification for fee pay if GA is free application type
```
[ ] Yes
[ ] No
```
> CIV-15544 Avoid dashboard fee pay notify for free GA

- src/main/java/uk/gov/hmcts/reform/civil/config/ExternalTaskListenerConfiguration.java
https://tools.hmcts.net/jira/browse/DTSCCI-947
DTSCCI-947: replicating configuration from civil-service to increase lock duration
```
[ ] Yes
[ ] No
```
> DTSCCI-947 replicating configuration from civil-service to increase lock duration

- src/main/java/uk/gov/hmcts/reform/civil/handler/tasks/GAResponseDeadlineTaskHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/tasks/GAResponseDeadlineTaskHandlerTest.java
https://tools.hmcts.net/jira/browse/DTSCCI-947
DTSCCI-947: prevent duplicates
```
[ ] Yes
[ ] No
```
> DTSCCI-947 prevent duplicates

- src/main/java/uk/gov/hmcts/reform/civil/handler/tasks/WaitCivilDocUpdatedTaskHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/tasks/WaitCivilDocUpdatedTaskHandlerTest.java
> CIV-16014 removed duplicate draft  documnet

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/CreateMakeDecisionDashboardNotificationForApplicantHandler.java
https://tools.hmcts.net/jira/browse/CIV-16040
enabled dashboard notifications for sequential lip applicant
```
[ ] Yes
[ ] No
```
> CIV-16040 enabled dashboard notifications for sequential lip applicant

- src/integrationTest/java/uk/gov/hmcts/reform/civil/controllers/CasesControllerTest.java
- src/main/java/uk/gov/hmcts/reform/civil/controllers/CasesController.java
- src/main/java/uk/gov/hmcts/reform/civil/service/CoreCaseDataService.java
- src/test/java/uk/gov/hmcts/reform/civil/service/CoreCaseDataServiceTest.java
https://tools.hmcts.net/jira/browse/CIV-15684
```
[ ] Yes
[x] No
```
> CIV-15684 present more than 10 result

- charts/civil-general-applications/values.preview.template.yaml
Configured role assignment url for civil service preview pod
```
[ ] Yes
[ ] No
```
> CIV-15377 - Configure Role Assignments Url 

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/businessprocess/DispatchBusinessProcessCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/businessprocess/EndGeneralAppBusinessProcessCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/businessprocess/EndHearingScheduledBusinessProcessCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/docmosis/GeneratePDFDocumentCallbackHandler.java
https://tools.hmcts.net/jira/browse/DTSCCI-305
> DTSCCI-305 Case id instead of case data

- .github/workflows/main.yml
DTSCCI-0000: Allow colon in PR title
```
[ ] Yes
[ ] No
```
> DTSCCI-0000: Allow colon in PR title

- src/main/java/uk/gov/hmcts/reform/civil/service/JudicialNotificationService.java
- src/main/java/uk/gov/hmcts/reform/civil/service/ParentCaseUpdateHelper.java
- src/test/java/uk/gov/hmcts/reform/civil/service/JudicialApplicantNotificationServiceTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/ParentCaseUpdateHelperTest.java
- [ x] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/CIV-15934
https://tools.hmcts.net/jira/browse/CIV-15935
https://tools.hmcts.net/jira/browse/CIV-16215
GA Lip - Duplicate email notification for Defendant when Judge makes decision on multiple …
> CIV-15934 unable to open document from claimant collection

- src/main/java/uk/gov/hmcts/reform/civil/service/JudicialDecisionHelper.java
- src/test/java/uk/gov/hmcts/reform/civil/service/JudicialDecisionHelperTest.java
https://tools.hmcts.net/jira/browse/CIV-15815
```
[ ] Yes
[x] No
```
> CIV-15815 remove logic to show the pay the additional fee button

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/payment/ModifyStateAfterAdditionalFeeReceivedCallbackHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/payment/ModifyStateAfterAdditionalFeeReceivedCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-16348
Check addnl payment status before progressing
```
[ ] Yes
[x] No
```
> CIV-16348 Check addnl payment status before progressing

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/CreateMakeDecisionDashboardNotificationForRespondentHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/CreateMakeDecisionDashboardNotificationForRespondentHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-16371
Fix respondent notification not sent
```
[ ] Yes
[x] No
```
> CIV-16371 Fix respondent notification not sent

- src/main/java/uk/gov/hmcts/reform/civil/service/DashboardNotificationsParamsMapper.java
- src/test/java/uk/gov/hmcts/reform/civil/service/DashboardNotificationsParamsMapperTest.java
https://tools.hmcts.net/jira/browse/CIV-16316
```
[ ] Yes
[x] No
```
> CIV-16316 amend welsh

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/CreateMakeDecisionDashboardNotificationForApplicantHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/CreateMakeDecisionDashboardNotificationForApplicantHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-16019
added to show order made notification for judge made decision on Additional response time expired
```
[ ] Yes
[ ] No
```
> CIV-16019 added to show order made notification for judge made decision on Additional response time expired

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/CreateMakeDecisionDashboardNotificationForRespondentHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/CreateMakeDecisionDashboardNotificationForRespondentHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-16388
added code to show order made notification
```
[ ] Yes
[ ] No
```
> CIV-16388 added code to show order made notification

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/CreateMakeDecisionDashboardNotificationForApplicantHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/dashboardnotifications/CreateMakeDecisionDashboardNotificationForApplicantHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-16432
Fix addl payment notification after response time expired
```
[ ] Yes
[x] No
```
> CIV-16432 Fix addl payment notification after response time expired

- charts/civil-general-applications/values.aat.template.yaml
- charts/civil-general-applications/values.preview.template.yaml
> CIV-00000 update preview and aat chats for camunda image

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToJudgeAddlnInfoHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToJudgeAddlnInfoHandlerTest.java
… responds to application
https://tools.hmcts.net/jira/browse/CIV-16553
Removed Response Submitted notification when applicant or Respondent responds to addl document
``` …
```
> CIV-16553 Dashboard notification - update delete list for 'Judge has requested more information'

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/model/genapplication/GAJudgesHearingListGAspec.java
- src/main/java/uk/gov/hmcts/reform/civil/service/JudicialTimeEstimateHelper.java
- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/hearingorder/HearingOrderGenerator.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/JudicialTimeEstimateHelperTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/docmosis/hearingorder/HearingOrderGeneratorTest.java
https://tools.hmcts.net/jira/browse/CIV-16579
Build hearing estimate text from days/hrs/mins
```
[ ] Yes
[x] No
```
> CIV-16579 Build hearing estimate text from days/hrs/mins

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandler.java
https://tools.hmcts.net/jira/browse/CIV-16575
```
[ ] Yes
[x] No
```
> CIV-16575 fix issue

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/service/JudicialDecisionHelper.java
- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/dismissalorder/DismissalOrderGenerator.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/JudicialDecisionHelperTest.java
https://tools.hmcts.net/jira/browse/CIV-16560
Application cloaked should be set for urgent , consent and withNotice applications for Lip cases
```
[ ] Yes
[x ] No
```
> CIV-16560 Amendments to Judge's journey - GA for LiPs

- src/main/java/uk/gov/hmcts/reform/civil/service/JudicialNotificationService.java
- src/test/java/uk/gov/hmcts/reform/civil/service/JudicialApplicantNotificationServiceTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/JudicialDecisionRespondentNotificationHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-16619
```
[ ] Yes
[x] No
```
> CIV-16619 hearing order notification

- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandler.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/JudicialDecisionHandlerTest.java
https://tools.hmcts.net/jira/browse/CIV-16576
```
[ ] Yes
[x] No
```
> CIV-16576 add optional

- bin/add-roles.sh
DTSCCI-1074 Add new doc removal role
DTSCCI-1074 Add new doc removal role
> DTSCCI-1074 Add new doc removal role

- src/main/java/uk/gov/hmcts/reform/civil/model/Party.java
- src/main/java/uk/gov/hmcts/reform/civil/model/caseflags/FlagDetail.java
- src/main/java/uk/gov/hmcts/reform/civil/model/caseflags/Flags.java
https://tools.hmcts.net/jira/browse/DTSCCI-1568
Add Flags to Party model
```
[ ] Yes
[ ] No
```
> DTSCCI-1568: Add Flags to Party model

- bin/add-roles.sh
> DTSCCI-000 - add roles

- bin/add-roles.sh
https://tools.hmcts.net/jira/browse/CIV-17037
Added new role to access profile.
NA
```
[ ] Yes
[x] No
```
> CIV-17037 - Pre-requisite changes for work allocating to WLU

- build.gradle
- config/owasp/suppressions.xml
- src/integrationTest/java/uk/gov/hmcts/reform/civil/controllers/BaseIntegrationTest.java
- src/main/java/uk/gov/hmcts/reform/civil/config/ApiAuthCheckerConfiguration.java
- src/main/java/uk/gov/hmcts/reform/civil/config/SecurityConfiguration.java
[DTSCCI-1556](https://tools.hmcts.net/jira/browse/DTSCCI-1556)
Remove JWT validation from Spring Security
> DTSCCI-1556 Remove JWT validation from Spring Security

- src/contractTest/java/uk/gov/hmcts/reform/civil/FeesLookupApiConsumerTest.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/payment/AdditionalPaymentsReferenceCallbackHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/service/GeneralAppFeesService.java
- src/main/java/uk/gov/hmcts/reform/civil/service/JudicialDecisionHelper.java
- src/main/java/uk/gov/hmcts/reform/civil/service/JudicialNotificationService.java
- src/main/java/uk/gov/hmcts/reform/civil/service/StateGeneratorService.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/fee/AdditionalFeeValueCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/camunda/payment/AdditionalPaymentsReferenceCallbackHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/GeneralAppFeesServiceTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/JudicialApplicantNotificationServiceTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/JudicialDecisionHelperTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/StateGeneratorServiceTest.java
https://tools.hmcts.net/jira/browse/CIV-16796
GA - Set Aside Judgment - Fee Code Change
```
[ ] Yes
[x ] No
```
> CIV-16796 Remove separate fee for Set Aside application

- src/main/java/uk/gov/hmcts/reform/civil/config/SecurityConfiguration.java
- src/main/java/uk/gov/hmcts/reform/civil/security/CustomAuthCheckerUserOnlyFilter.java
- src/test/java/uk/gov/hmcts/reform/civil/security/CustomAuthCheckerUserOnlyFilterTest.java
DTSCCI-2066: Custom Authorisation Filter
> DTSCCI-2066: Custom Authorisation Filter

- config/owasp/suppressions.xml
[DTSCCI-2098](https://tools.hmcts.net/jira/browse/DTSCCI-2098)
DTSCCI-2079: Tomcat suppressions
> DTSCCI-2079: Tomcat suppressions

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToJudgeAddlnInfoHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToWrittenRepresentationHandler.java
- src/main/java/uk/gov/hmcts/reform/civil/launchdarkly/FeatureToggleService.java
- src/main/java/uk/gov/hmcts/reform/civil/utils/DocUploadUtils.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondToJudgeAddlnInfoHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/handler/callback/user/RespondWrittenRepresentationHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/civil/launchdarkly/FeatureToggleServiceTest.java
- src/test/java/uk/gov/hmcts/reform/civil/util/DocUploadUtilsTest.java
https://tools.hmcts.net/jira/browse/DTSCCI-2211
https://tools.hmcts.net/jira/browse/CIV-17186
Respondent solicitor cannot respond on GA claim due to case data validation failure
**Does this PR introduce a breaking change?** (check one …
> CIV-17186 added feature toggle for welsh fields

- src/main/java/uk/gov/hmcts/reform/civil/service/search/ElasticSearchService.java
> DTSCCI-0000 Add logging

- src/main/java/uk/gov/hmcts/reform/civil/config/SecurityConfiguration.java
- src/main/java/uk/gov/hmcts/reform/civil/controllers/testingsupport/TestingSupportController.java
https://tools.hmcts.net/jira/browse/DTSCCI-2237
Add flowstate endpoint
```
[ ] Yes
[ ] No
```
> DTSCCI-2237 Add flowstate endpoint

- bin/run-api-tests.sh
- build.gradle
> DTSCCI-2243 Remove Run All Tests When There Are No Failed Tests

- bin/run-api-tests.sh
> DTSCCI-000 Clean Up FT Runner

- .github/workflows/ado_artifacts_build.yml
- Jenkinsfile_CNP
- build.gradle
- src/test/java/uk/gov/hmcts/reform/civil/aspect/EventAllowedAspectTest.java
> DTSCCI-2086 swtich from jitpack

- config/owasp/suppressions.xml
> CIV-0000 Supress cve's

- Jenkinsfile_nightly
This reverts commit 11f288d2da9694468287c7d3a3cc798f1d531971.
```
[ ] Yes
[ ] No
```
> DTSCCI-000 Revert Remove fortify scan from nightly

- src/main/java/uk/gov/hmcts/reform/civil/service/docmosis/DocumentGeneratorService.java
> DTSCCI-2302 Add logging

- config/owasp/suppressions.xml
> DTSCCI-000 Add Suppression

- config/owasp/suppressions.xml
> CIV-0000 Supress CVE

- config/owasp/suppressions.xml
> CIV-00000 Update suppressions.xml

- build.gradle
> DTSCCI-2702: fix lib version

- charts/civil-general-applications/values.aat.template.yaml
- charts/civil-general-applications/values.preview.template.yaml
DTSCCI-938
point_to_ccd_image
```
[ ] Yes
[ ] No
```
> point to hard coded ccd image
